beautybisite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^$',views.index,name='index'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/',views.register,name='register'),
    url(r'^add_user/', views.add_user, name='add_user'),
    url(r'^userlist/', views.userlist, name='userlist'),
    url(r'^edit_user/(\d+)/$', views.edit_user, name='edit_user'),

    url(r'^del_user/(\d+)/$', views.del_user, name='del_user'),
    url(r'^testcharts/', views.testcharts, name='testcharts'),
]

templates/query/datamanger.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}

{% block somescript %}
    <div class="modal" id="myModal" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content" id="modalContent">
            </div>
        </div>
    </div>

    <div class="modal" id="myModal1" tabindex="-1" role="dialog"
         aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" id="modalContent">
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('abbr.order-info').click(function () {
                var order_id = $(this).attr("order_id");
                $('#myModal').modal({
                    remote: "/kucun/api/order_info/?order_id=" + order_id,
                    backdrop: "static"
                })
            });

            $('button.list').click(function () {
                var order_id = $(this).attr("order_id");
                $('#myModal1').modal({
                    remote: "/kucun/api/order_list/?order_id=" + order_id,
                    backdrop: "static"
                })
            });

            $('button.arrears').click(function () {
                var order_id = $(this).attr("order_id")
                $.post("/kucun/api/change_order_arrears/",
                        {
                            order_id: order_id
                        },
                        function (data, status) {
                            if (data == 'chaoguo') {
                                alert('库存量不足！')
                            } else {
                                $('#' + order_id).html(data)
                                alert('操作成功！\n重新刷新页面后，颜色即可显示正常')
                            }
                        });
            });

            $('body').on('hidden.bs.modal', '.modal', function () {
                $(this).removeData('bs.modal');
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>订单号</th>
                <th>客户</th>
                <th>总金额</th>
                <th>欠账</th>
                <th>日期</th>
                <th>清单</th>
            </tr>
            {% for order in orders %}
                <tr>
                    <td><abbr class="order-info" title="{{ order.remark }}"
                              order_id="{{ order.id }}" onclick="null">{{ order.name }}</abbr>
                    </td>
                    <td>{{ order.customer }}</td>
                    <td>{{ order.all_price }}</td>
                    <td>
                        {% if order.is_arrears %}
                            <button id="{{ order.id }}" type="button" class="btn btn-danger btn-xs arrears"
                                    order_id="{{ order.id }}">是
                            </button>
                        {% else %}
                            <button id="{{ order.id }}" type="button" class="btn btn-success btn-xs arrears"
                                    order_id="{{ order.id }}">否
                            </button>
                        {% endif %}
                    </td>
                    <td>{{ order.date|date:"Y.n.j" }}</td>
                    <td>
                        <button id="{{ order.id }}" type="button" class="btn btn-info btn-xs list"
                                order_id="{{ order.id }}">清单
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/query/modelbase.html
<!DOCTYPE html>
<html>
<head>
    {% block somescript %}{% endblock %}
    {% block otherstyle %}{% endblock %}
</head>
<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/query/productlist.html
{% extends "base.html" %}
{% block title %}改价记录{% endblock %}
{% block content %}
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>商品名</th>
                <th>类型</th>
                <th>原价</th>
                <th>现价</th>
                <th>操作时间</th>
                <th>操作人</th>
            </tr>
            {% for change_price in change_prices %}
                <tr class="{% if change_price.old_price > change_price.new_price %}success{% else %}danger{% endif %}">
                    <td>{{ change_price.goods }}</td>
                    <td>
                        {% if change_price.goods.goods_type == 0 %}
                            手机
                        {% elif change_price.goods.goods_type == 1 %}
                            配件
                        {% endif %}
                    </td>
                    <td>{{ change_price.old_price }}</td>
                    <td>{{ change_price.new_price }}</td>
                    <td>{{ change_price.date|date:"Y.n.j H:i" }}</td>
                    <td>{{ change_price.updater }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
{% endblock %}

templates/query/querylist.html
{% extends "modal_base.html" %}
{% block otherstyle %}
    <style>
        .table.list {
            max-width: 570px;
        }

        .modal-header {
            max-width: 570px;
        }

    </style>
{% endblock %}

{% block somescript %}
{% endblock %}

{% block content %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><b style="color: #ff000a">{{ order.name }}</b>订单详情
        </h4>
    </div>
    <table class="table table-striped list">
        <tr>
            <th>商品</th>
            {% if request.user.is_superuser %}
                <th>进价</th>
            {% endif %}
            <th>售价</th>
            <th>数量</th>
            <th>合计</th>
        </tr>
        {% for sell_record in sell_records %}
            <tr>
                <td>{{ sell_record.goods }}</td>
                {% if request.user.is_superuser %}
                    <td>{{ sell_record.average_price }}</td>
                {% endif %}
                <td>{{ sell_record.sell_price }}</td>
                <td>{{ sell_record.sell_num }}</td>
                <td>{{ sell_record.get_receivable }}</td>
            </tr>
        {% endfor %}

    </table>
{% endblock %}

templates/query/userinfo.html
{% extends "base.html" %}
{% load pagetag %}
{% block title %}客户信息{% endblock %}

{% block content %}
<form class="form-horizontal" method="post"> {% csrf_token %}
        {% for item in user_info %}
          <div class="form-group">
            {% if item.field.required %}
              <label class="col-sm-2 control-label">*{{ item.label }}</label>
            {% else %}
                <label style="font-weight: normal" class="col-sm-2 control-label">{{ item.label }}</label>
            {% endif %}

            <div class="col-sm-10">
              {{ item }}
            </div>
          </div>
        {% endfor %}
        <div class="pull-right col-sm-pull-11">
            <button type="submit" class="btn btn-success">保存数据</button>
        </div>

    </form>
{% endblock %}}

templates/query/userlist.html
{% extends "base.html" %}
{% load pagetag %}
{% block title %}客户信息列表{% endblock %}

{% block content %}
<table class="table table-bordered">
  <thead>
        <tr>
            <td>ID</td>
            <td>会员id</td>
            <td>会员类型</td>
            <td>昵称</td>
            <td>用户名</td>
            <td>生日</td>
            <td>性别</td>
            <td>更新时间</td>
            <td>状态</td>
            <td>添加人</td>
            <td>操作</td>
        </tr>
  </thead>
        <tbody>
            {% for customer in user_list  %}
                <tr>
                    <td><a href="{% url 'users:edit_user' customer.user_id %}">{{customer.user_id}}</a></td>
                    <td>{{customer.user_id}}</td>
                    <td>{{customer.user_type|upper}}</td>
                    <td>{{customer.nickname}}</td>
                    <td>{{customer.username}}</td>
                    <td>{{customer.birthday}}</td>
                    <td>{{customer.gender|truncatechars:10}}</td>
                    <td>{{customer.update_date}}</td>
                    <td class="{{ customer.is_delete }}">{{customer.is_delete}}</td>
                    <td>{{customer.add_people_id}}</td>
                    <td>
                        <a href="{% url 'users:del_user' customer.user_id %}">删除</a>
                        |
                        <a href="{% url 'users:edit_user' customer.user_id %}">编辑</a>
                    </td>>
                </tr>
            {% endfor %}
        </tbody>
</table>

<nav aria-label="Page navigation">
  <ul class="pagination">
      {% if user_list.has_previous %}
          <li>
              <a href="?page={{ user_list.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}

    {%  for pg in user_list.paginator.page_range %}
        {% circle_page user_list.number pg %}
    {% endfor %}

    {% if user_list.has_next %}
        <li>
          <a href="?page={{ user_list.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
    {% endif %}
  </ul>
</nav>

{% endblock %}}