beautybisite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls')),
    url(r'^users/',include('django.contrib.auth.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^$',views.index,name='index'),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/',views.register,name='register'),
    url(r'^add_user/', views.add_user, name='add_user'),
    url(r'^userlist/', views.userlist, name='userlist'),
    url(r'^edit_user/(\d+)/$', views.edit_user, name='edit_user'),

    url(r'^del_user/(\d+)/$', views.del_user, name='del_user'),
    url(r'^testcharts/', views.testcharts, name='testcharts'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/jquery/2.1.0/jquery.min.js" type="text/javascript"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="http://cdn.bootcss.com/Chart.js/0.2.0/Chart.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    {% block somescript %}{% endblock %}

    <style>
        body {
            background-color: #eee;
            padding-top: 70px;
            padding-bottom: 30px;
        }
        .theme-dropdown .dropdown-menu {
            position: static;
            display: block;
            margin-bottom: 20px;
        }
        .theme-showcase > p > .btn {
            margin: 5px 0;
        }
        .theme-showcase .navbar .container {
            width: auto;
        }
    </style>
    {% block otherstyle %}{% endblock %}
</head>
<body>
{% block top %}
    <div role="navigation" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"  style="color: #5c79dc" href="{% url "index" %}">{{ header }} <span
                        class="badge"  >{{ amount }}</span></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">数据查询<span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{% url "users:userlist" %}">用户列表</a></li>
                            <li><a href="{% url "users:add_user" %}">添加用户</a></li>
                        </ul>
                    </li>
                    {% if request.user.is_superuser %}
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">数据上传<span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="{% url "users:add_user" %}">文件上传</a></li>
                                <li><a href="{% url "users:add_user" %}">文件下载</a></li>
                            </ul>
                        </li>
                    {%endif%}
                    {% if not request.user.is_superuser %}
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">其他<span class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="{% url "users:add_user" %}">暂未开放</a></li>
                                <li><a href="{% url "users:add_user" %}">暂未开放</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">测试<span
                                    class="caret"></span></a>
                            <ul role="menu" class="dropdown-menu">
                                <li><a href="{% url "users:add_user" %}">用户列表</a></li>
                                <li><a href="{% url "users:add_user" %}"><font color="red">排行</font></a>
                                </li>
                            </ul>
                        </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><a>欢迎，{{ request.user }}</a></li>
                        <li><a style="color: cornflowerblue" href="{% url "logout" %}?next={{ request.path }}">退出登录</a></li>
                        <li><a style="color: cornflowerblue" href="{% url "password_change" %}?next={{ request.path }}">修改密码</a></li>
                    {% else %}
                        <li><a style="color: #5c79dc" href="{% url "login" %}?next={{ request.path }}">登录</a></li>
                        <li><a style="color: #5c79dc" href="{% url "users:register" %}?next={{ request.path }}">登录</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
{% endblock %}
<div>
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load pagetag %}
{% block title %}客户信息列表{% endblock %}

{% block content %}
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo">
                <a href="{% url 'index' %}">测试页面</a>
            </h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a></button>
                <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a></button>
                </p>

            {% endif %}
        </div>
    </div>
</div>
{% endblock %}}